---
title: "ANCOVAA"
output: html_document
date: "2023-06-07"
---

```{r setup, include=FALSE}
# Thesis Preliminary Analyses
  #data stuff
library(tidyverse)
library(dplyr)
  #CSV/CAV files
library(haven)
  #EDA stuff
library(kableExtra)
options(knitr.table.format = "html") 

## Prepare Data For Analysis 

#### Import & Select data

### Import dataset 
NHRVS_2019 <- read_sav("~/Desktop/Adams_lab/SPSS_stuff/NHRVS_2019_2020_FINAL_weighted.sav")

### Select and rename Variables
thesis_NHRVS <- dplyr::select(NHRVS_2019,
    #Background Variables __________
      caseid,weight,Age,Male_Gender,White_Race,SomeCollege_or_Higher,
      Married_Partnered,Income_60k_plus,YN_work,
      PCS_FINAL,MCS_FINAL,Weight_kg,BMI,
    #Military variables__________
      Combat_Veteran,Years_in_Military,Branch_5cat,Enlistment_status_3cat,
      MilitaryRank_3cat,
    #Mental Health Variables___________
      TOTAL_TRAUMAS,DIRECT_TRAUMA_EXPS,LT_PCL_33,LT_MDD_Sx_only,LT_Suicide_4cat,Suicide_Attempt_LT,
      LT_Suicide_Plan,LT_AUD,LT_NicotineDep,LT_DUD,tot_MHC,Any_MHC,
    #Physical health Variables_________
      ANY_ADL_DISABILITY,ANY_IADL_DISABILITY,Any_Disability,tot_phc,Any_PHC,Q22A_1,Q22A_2,
      Q22A_3,Q22A_4,Q22A_5,Q22A_6,Q22A_7,Q22A_8,Q22A_9,Q22A_10,Q22A_11,Q22B_1,
      Q22B_2,Q22B_3,Q22B_4,Q22B_5,
    #Exercise variables ___________
      godin_mild_winsor,godin_Mod_winsor,godin_Stren_winsor,HCS,HCS_Cats,
      godin_total_ac,god3cat,god2cat,GODIN_outliers)
    
#Rename variabes
thesis_NHRVS <- rename(thesis_NHRVS,
      MET_total = godin_total_ac,
      God_mild = godin_mild_winsor,
      God_mod = godin_Mod_winsor,
      God_stren = godin_Stren_winsor,
      College = SomeCollege_or_Higher,
      MCS = MCS_FINAL,
      PCS = PCS_FINAL,
      Arthritis = Q22A_1,
      Athsma =  Q22A_2,
      Cancer = Q22A_3,
      Chron_pain = Q22A_4,
      Liv_dis = Q22A_5,
      Diabetes = Q22A_6,
      Hrt_dis = Q22A_7,
      Hrt_atk = Q22A_8,
      High_chol = Q22A_9,
      High_bld_press = Q22A_10,
      Kid_dis = Q22A_11,
      Migrane = Q22B_1,
      MS = Q22B_2,
      Osteoporosis = Q22B_3,
      Rhum_arth = Q22B_4,
      Stroke = Q22B_5,
      LT_MDD = LT_MDD_Sx_only,
      LT_PTSD = LT_PCL_33
)
# We need exercsie variables that are in MET minutes, not just HCS. 
# We also need to create demographic and health variables

thesis_NHRVS<- thesis_NHRVS %>%
  # First Create all of the variables
  mutate(thesis_NHRVS, 
    # Exercise variables
         Ex_time = (God_mild + God_mod + God_stren)*15,
            # Tells us how long people exercised for.
         MET_min = MET_total* 15,
         MET_min_W = ifelse(MET_min > 2500, 2500, MET_min),
            # Total METs per week times the duration of exercise
         Ex_rec = as.factor(ifelse(MET_min >= 500, "Sufficient", "Insufficient")),
            # Meeting activity levels (i.e., sufficient vs insufficient)
         Ex_3cat = as.factor(ifelse(MET_min < 290, 1,
                              ifelse(MET_min < 500 & MET_min >= 290, 2,3))),
         Ex_4cats = as.factor(ifelse(MET_min < 290, "Sed",
                              ifelse(MET_min < 500 & MET_min >= 290, "Mod",
                              ifelse(MET_min < 1000 & MET_min >= 500, "Active", 
                              ifelse(MET_min < 2000 & MET_min >= 1000, "Super", NA))))),
         Ex_3catW = as.factor(ifelse(MET_min_W < 290, 1,
                              ifelse(MET_min_W < 500 & MET_min_W >= 290, 2,3))),
         Ex_4catsW = as.factor(ifelse(MET_min_W < 290, "Sed",
                              ifelse(MET_min_W < 500 & MET_min_W >= 290, "Mod",
                              ifelse(MET_min_W < 1000 & MET_min_W >= 500, "Active", 
                              ifelse(MET_min_W < 2500 & MET_min_W >= 1000, "Super", NA))))),
# 3 godin (HCS) categories converted to MET_min 
    # Other Variables 
         HCS_win = (God_mod*5) + (God_stren*9),
         HCS3cat = as.factor(ifelse(HCS_win < 14, "Insufficient",
                              ifelse(HCS_win < 24 & HCS_win >= 290, "Moderate", "Active"))),
         Yr5_Military = as.factor(ifelse(Years_in_Military >= 5, "5+", "<5")),
         Active_PA = as.factor(ifelse(Ex_3cat == 3,1,0)),
         Moderate_PA = as.factor(ifelse(Ex_3cat == 2,1,0)),
         Insuf_PA = as.factor(ifelse(Ex_3cat == 2,1,0)),
         Total_HC = Any_Disability + Arthritis + Cancer + Chron_pain + Liv_dis +
                    Diabetes + Hrt_dis + Hrt_atk + High_chol + High_bld_press +
                    Kid_dis + Migrane + MS + Osteoporosis + Rhum_arth + Stroke +
                    LT_MDD + LT_PTSD + LT_AUD + LT_DUD + LT_NicotineDep,
         Total_PHC = Any_Disability + Arthritis + Cancer + Chron_pain + Liv_dis +
                    Diabetes + Hrt_dis + Hrt_atk + High_chol + High_bld_press +
                    Kid_dis + Migrane + MS + Osteoporosis + Rhum_arth + Stroke,
        Total_MHC = LT_MDD + LT_PTSD + LT_AUD + LT_DUD + LT_NicotineDep,
    
    ) %>%
mutate(thesis_NHRVS,
      #Physical health variables
           Any_Disability = as.factor(Any_Disability),
           Arthritis = as.factor(Arthritis),
           Athsma = as.factor(Athsma),
           Cancer = as.factor(Cancer),
           Chron_pain = as.factor(Chron_pain),
           Liv_dis = as.factor(Liv_dis),
           Diabetes = as.factor(Diabetes),
           Hrt_dis = as.factor(Hrt_dis),
           Hrt_atk = as.factor(Hrt_atk),
           High_chol = as.factor(High_chol),
           High_bld_press = as.factor(High_bld_press),
           Kid_dis = as.factor(Kid_dis),
           Migrane = as.factor(Migrane),
           MS = as.factor(MS),
           Osteoporosis = as.factor(Osteoporosis),
           Rhum_arth = as.factor(Rhum_arth),
           Stroke = as.factor(Stroke),
           Ex_3cat = as.factor(Ex_3cat),  
           Male_Gender = as.factor(Male_Gender), 
           Married_Partnered = as.factor(Married_Partnered),
           White_Race = as.factor(White_Race),
           College = as.factor(College),
           Income_60k_plus = as.factor(Income_60k_plus),
           YN_work = as.factor(YN_work),
           Combat_Veteran = as.factor(Combat_Veteran),
           Any_MHC = as.factor(Any_MHC),
           Any_PHC = as.factor(Any_PHC),
           god2cat = as.factor(god2cat),
      #Mental health variables
          LT_Suicide_4cat = as.factor(LT_Suicide_4cat),
          LT_MDD = as.factor(LT_MDD),
          LT_PTSD = as.factor(LT_PTSD),
          LT_AUD = as.factor(LT_AUD),
          LT_DUD = as.factor(LT_DUD),
          LT_NicotineDep = as.factor(LT_NicotineDep)
    )

thesis_NHRVS <- mutate(thesis_NHRVS, 
        Ex_3cat = recode(Ex_3cat,
                         "1" = "Insufficient",
                         "2" = "Moderate",
                         "3" = "Active"),
        Married_Partnered = recode(Married_Partnered,
                         "0" = "Married_Partnered",
                         "1" = "Single"),
        Male_Gender = as.factor(Male_Gender),
        Male_Gender = recode(Male_Gender,
                         "0" = "Female",
                         "1" = "Male"),
        White_Race = recode(White_Race,
                         "0" = "Not_White",
                         "1" = "White"),
        College = recode(College,
                         "0" = "No_Colege",
                         "1" = "Some_Colege"),
        Income_60k_plus = recode(Income_60k_plus,
                         "0" = "Under_60k",
                         "1" = "OVer_60k"),
        YN_work = recode(YN_work,
                         "1" = "No_Work",
                         "2" = "Working"),
        Combat_Veteran = as.factor(Combat_Veteran),
        Combat_Veteran = recode(Combat_Veteran,
                         "0" = "No_Combat",
                         "1" = "Combat"),
        Any_MHC = recode(Any_MHC,
                         "0" = "No_con",
                         "1" = "MHC"),
        Any_PHC = recode(Any_PHC,
                         "0" = "No_con",
                         "1" = "PHC"),
        LT_Suicide_4cat = as.factor(LT_Suicide_4cat),
        LT_Suicidal = recode(LT_Suicide_4cat,
                         "0" = "0",
                         "1" = "0",
                         "2" = "1",
                         "3" = "1"
                             ))

#Filter out NA values
thesis_NHRVS <- thesis_NHRVS %>%
  filter(!is.na(Ex_rec)) %>%
  filter(!is.na(Ex_3cat)) %>%
  filter(!is.na(MCS)) %>%
  filter(!is.na(PCS)) %>%
  filter(!is.na(BMI)) %>%
  filter(!is.na(Any_Disability)) %>%
  filter(!is.na(Arthritis)) %>%
  filter(!is.na(Cancer)) %>%
  filter(!is.na(Chron_pain)) %>%
  filter(!is.na(Liv_dis)) %>%
  filter(!is.na(Diabetes)) %>%
  filter(!is.na(Hrt_dis)) %>%
  filter(!is.na(Hrt_atk)) %>%
  filter(!is.na(High_chol)) %>%
  filter(!is.na(High_bld_press)) %>%
  filter(!is.na(Kid_dis)) %>%
  filter(!is.na(Migrane)) %>%
  filter(!is.na(MS)) %>%
  filter(!is.na(Osteoporosis)) %>%
  filter(!is.na(Rhum_arth)) %>%
  filter(!is.na(Stroke)) %>%
  filter(!is.na(LT_MDD)) %>%
  filter(!is.na(LT_PTSD)) %>%
  filter(!is.na(LT_AUD)) %>%
  filter(!is.na(LT_DUD)) %>%
  filter(!is.na(LT_NicotineDep)) %>%
  filter(!is.na(LT_Suicidal))
#$View(thesis_NHRVS)
thesis_NHRVS
library(MASS)
library(nnet)
library(performance)
```

summary of data
```{r}
summary(thesis_NHRVS$TOTAL_TRAUMAS,)

before_Adj<-  thesis_NHRVS %>%
            group_by(Ex_3cat) %>%  
            summarise(mean_Dtrauma = mean(DIRECT_TRAUMA_EXPS),
            sd_Dtrauma = sd(DIRECT_TRAUMA_EXPS),
            mean_Ttrauma = mean(TOTAL_TRAUMAS),
            sd_Ttrauma = sd(TOTAL_TRAUMAS))
  
before_Adj  

#windsorize 
thesis_test <- thesis_NHRVS %>%
  mutate(
    DIRECT_TRAUMA_EXPS = ifelse(DIRECT_TRAUMA_EXPS >= (mean(DIRECT_TRAUMA_EXPS) + (2*sd(DIRECT_TRAUMA_EXPS))), round(mean(DIRECT_TRAUMA_EXPS)+(2*sd(DIRECT_TRAUMA_EXPS)),0), DIRECT_TRAUMA_EXPS),
    TOTAL_TRAUMAS_W = ifelse(TOTAL_TRAUMAS >= (mean(TOTAL_TRAUMAS) + (2*sd(TOTAL_TRAUMAS))), round(mean(TOTAL_TRAUMAS)+(2*sd(TOTAL_TRAUMAS)),0), TOTAL_TRAUMAS),                          
    TOTAL_TRAUMAS_OUT = 
      ifelse(TOTAL_TRAUMAS >= (mean(TOTAL_TRAUMAS) + (3*sd(TOTAL_TRAUMAS))), NA,TOTAL_TRAUMAS),
    Trauma_out_inv = 1/TOTAL_TRAUMAS_OUT,
    Trauma_out_sqrt = (TOTAL_TRAUMAS_OUT)^(1/2)
  )
    
  
hist(thesis_test$TOTAL_TRAUMAS_OUT)
hist(thesis_test$Trauma_out_inv)
hist(thesis_test$Trauma_out_sqrt)

```


```{r}
thesis_test%>%
            group_by(Ex_3cat) %>%  
            summarise(mean_Dtrauma = mean(TOTAL_TRAUMAS_OUT),
            sd_Dtrauma = sd(TOTAL_TRAUMAS_OUT),
            mean_Ttrauma = mean(TOTAL_TRAUMAS),
            sd_Ttrauma = sd(TOTAL_TRAUMAS))

plot(thesis_test$Ex_3cat,thesis_test$DIRECT_TRAUMA_EXPS)
plot(thesis_test$Ex_3cat,thesis_test$TOTAL_TRAUMAS)



boxplot(TOTAL_TRAUMAS ~ Ex_3cat,
data = thesis_NHRVS,
main = "Number of traumas withith exercise cat",
xlab = "ex_cat",ylab = "# of traumas",
col = "red",border = "black")



boxplot(TOTAL_TRAUMAS ~ Ex_3cat,
data = thesis_test,
main = "Number of traumas withith exercise cat",
xlab = "ex_cat",ylab = "# of traumas",
col = "blue",border = "black")
```

assumptions
```{r}
ggline(thesis_test, x = "Ex_3cat", y = "TOTAL_TRAUMAS_W", 
       add = c("mean_se"))

library(emmeans)
library(rstatix)
pwc <- thesis_test %>% 
  emmeans_test(
    TOTAL_TRAUMAS_W ~ Ex_3cat, covariate = Age + thesis_test$College + thesis_test$Income_60k_plus + thesis_test$YN_work + thesis_test$BMI,
    p.adjust.method = "bonferroni"
    )
pwc


?emmeans_test()

https://www.carlosivanrodriguez.com/guides/anova/ancova/
```



running ancoova

```{r}

library(tidyverse)
library(ggpubr)
library(rstatix)
library(broom)
#library(car)



thesis_test$Trauma_out_sqrt
  
summary(thesis_NHRVS$TOTAL_TRAUMAS_OUT)

model <- aov(TOTAL_TRAUMAS_OUT ~ Ex_3cat, data = thesis_test)
summary(model)
levene_test(TOTAL_TRAUMAS ~ Ex_3cat, data = thesis_test)

ancova_model <- aov(thesis_test$Trauma_out_sqrt ~ Ex_3cat + Age + College + Income_60k_plus + YN_work + BMI, data = thesis_test)
Anova(ancova_model, type="III")



```

plotting them
```{r}
# if (!require(remotes)) {
#     install.packages("remotes")
# }
# remotes::install_github('jorvlan/raincloudplots')

library(raincloudplots)


dim(thesis_test)
thesis_test %>%
  group_by(Ex_3cat)
  

df_1x1 <- data_1x1(
  array_1 = ,
  array_2 = iris$Sepal.Length[51:100],
  jit_distance = .09,
  jit_seed = 321)

head(df_1x1)

tail(df_1x1)


raincloud_1_v <- raincloud_1x1(
  data = df_1x1, 
  colors = (c('dodgerblue','darkorange')), 
  fills = (c('dodgerblue','darkorange')), 
  size = 1, 
  alpha = .6, 
  ort = 'v') +

scale_x_continuous(breaks=c(1,2), labels=c("Group1", "Group2"), limits=c(0, 3)) +
  xlab("Groups") + 
  ylab("Score") +
  theme_classic()

raincloud_1_v
```


```{r}
#install.packages("tidyquant")
library(tidyquant)
library(ggdist)
library(ggthemes)


hist(thesis_test$TOTAL_TRAUMAS_OUT)

sum(is.na(thesis_test$TOTAL_TRAUMAS_OUT))


```


```{r}
thesis_test %>% 
  # filter() %>% 
  ggplot(aes(x = factor(Ex_3cat), y = TOTAL_TRAUMAS_W, fill = factor(Ex_3cat), colour = factor(Ex_3cat))) +
  
  # add half-violin from {ggdist} package
  stat_halfeye(
    # adjust bandwidth
    adjust = 0.5,
    # move to the right
    justification = -0.2,
    # remove the slub interval
    .width = 0,
    width = .6,
    point_colour = NA,
    size = .01
  ) +
  geom_boxplot(
    width = 0.15,
    color = "black",
    # removing outliers
    alpha = 1,
    position= position_nudge(x=.1)
  ) +
  geom_jitter(
    size = .5,
    alpha = .3,
     width = .08,
  )+
  # Themes and Labels
  #scale_fill_tableau("Tableau 20", name = NULL) +
  labs(
    title = "Total Number of Traumas by Physical Activity Level",
    x = "Physical Activity Level",
    y = "Total Number of Traumas ",
    fill = "Activity level"
  ) +
  coord_flip() +
  theme_classic() +
  scale_fill_manual(values=c("#156064","#00c49a","#00a9a5")) +
  scale_color_manual(values=c("#156064","#00c49a","#00a9a5")) +
  theme(legend.position = "none")

```


