---
title: "Combined_FP"
output: html_document
date: "2023-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install package:
```{r}
# install.packages("devtools")
devtools::install_github("NightingaleHealth/ggforestplot",force = TRUE)
```

Usage: 
```{r}
# Load tidyverse and ggforestplot
# install.packages("tidyverse")
# library(tidyverse)
# library(ggforestplot)

# Get subset of example, linear associations, data frame
df_linear <-
  ggforestplot::df_linear_associations |>
  dplyr::arrange(name) |>
  dplyr::filter(dplyr::row_number() <= 30)

df_linear

# Forestplot
forestplot(
  df = df_linear,
  estimate = beta,
  logodds = FALSE,
  colour = trait,
  title = "Associations to metabolic traits",
  xlab = "1-SD increment in cardiometabolic trait
  per 1-SD increment in biomarker concentration"
)

```

```{r}
# Get subset of example, log odds ratios, data frame
df_logodds <-
  df_logodds_associations |>
  dplyr::arrange(name) |>
  dplyr::left_join(ggforestplot::df_NG_biomarker_metadata, by = "name") |> 
  dplyr::filter(group == "Amino acids") |>
  # Set the study variable to a factor to preserve order of appearance
  # Set class to factor to set order of display.
  dplyr::mutate(
    study = factor(
      study,
      levels = c("Meta-analysis", "NFBC-1997", "DILGOM", "FINRISK-1997", "YFS")
    )
  )

# Forestplot
forestplot(
  df = df_logodds,
  estimate = beta,
  logodds = TRUE,
  colour = study,
  shape = study,
  title = "Associations to type 2 diabetes",
  xlab = "Odds ratio for incident type 2 diabetes (95% CI)
  per 1−SD increment in metabolite concentration"
) +
  # You may also want to add a manual shape scale to mark meta-analysis with a
  # diamond shape
  ggplot2::scale_shape_manual(
    values = c(23L, 21L, 21L, 21L, 21L),
    labels = c("Meta-analysis", "NFBC-1997", "DILGOM", "FINRISK-1997", "YFS")
  )
```

