---
title: "Multinomial_output"
output: html_document
date: "2023-04-04"
---
```{r setup, include=FALSE}
# Thesis Preliminary Analyses
  #data stuff
library(tidyverse)
library(dplyr)
  #CSV/CAV files
library(haven)
  #EDA stuff
library(ggplot2)
  #figures
library(kableExtra)
  #knitted tables

options(knitr.table.format = "html") 

## Prepare Data For Analysis 

#### Import & Select data

### Import dataset 
setwd("~/Desktop/Adams_lab/SPSS_stuff")
NHRVS_2019 <- read_sav("~/Desktop/Adams_lab/SPSS_stuff/NHRVS_2019_2020_FINAL_weighted.sav")

### Select and rename Variables
thesis_NHRVS <- dplyr::select(NHRVS_2019,
    #Background Variables __________
      caseid,weight,Age,Male_Gender,White_Race,SomeCollege_or_Higher,
      Married_Partnered,Income_60k_plus,YN_work,
      PCS_FINAL,MCS_FINAL,Weight_kg,BMI,
    #Military variables__________
      Combat_Veteran,Years_in_Military,Branch_5cat,Enlistment_status_3cat,
      MilitaryRank_3cat,
    #Mental Health Variables___________
      TOTAL_TRAUMAS,LT_PCL_33,LT_MDD_Sx_only,LT_Suicide_4cat,Suicide_Attempt_LT,
      LT_Suicide_Plan,LT_AUD,LT_NicotineDep,LT_DUD,tot_MHC,Any_MHC,
    #Physical health Variables_________
      ANY_ADL_DISABILITY,ANY_IADL_DISABILITY,Any_Disability,tot_phc,Any_PHC,Q22A_1,Q22A_2,
      Q22A_3,Q22A_4,Q22A_5,Q22A_6,Q22A_7,Q22A_8,Q22A_9,Q22A_10,Q22A_11,Q22B_1,
      Q22B_2,Q22B_3,Q22B_4,Q22B_5,
    #Exercise variables ___________
      godin_mild_winsor,godin_Mod_winsor,godin_Stren_winsor,HCS,HCS_Cats,
      godin_total_ac,god3cat,god2cat,GODIN_outliers)
    
#Rename variabes
thesis_NHRVS <- rename(thesis_NHRVS,
      MET_total = godin_total_ac,
      God_mild = godin_mild_winsor,
      God_mod = godin_Mod_winsor,
      God_stren = godin_Stren_winsor,
      College = SomeCollege_or_Higher,
      MCS = MCS_FINAL,
      PCS = PCS_FINAL,
      Arthritis = Q22A_1,
      Athsma =  Q22A_2,
      Cancer = Q22A_3,
      Chron_pain = Q22A_4,
      Liv_dis = Q22A_5,
      Diabetes = Q22A_6,
      Hrt_dis = Q22A_7,
      Hrt_atk = Q22A_8,
      High_chol = Q22A_9,
      High_bld_press = Q22A_10,
      Kid_dis = Q22A_11,
      Migrane = Q22B_1,
      MS = Q22B_2,
      Osteoporosis = Q22B_3,
      Rhum_arth = Q22B_4,
      Stroke = Q22B_5,
      LT_MDD = LT_MDD_Sx_only,
      LT_PTSD = LT_PCL_33
)
# We need exercsie variables that are in MET minutes, not just HCS. 
# We also need to create demographic and health variables

thesis_NHRVS<- thesis_NHRVS %>%
  # First Create all of the variables
  mutate(thesis_NHRVS, 
    # Exercise variables
         Ex_time = (God_mild + God_mod + God_stren)*15,
            # Tells us how long people exercised for.
         MET_min = MET_total* 15,
         MET_min_W = ifelse(MET_min > 2500, 2500, MET_min),
            # Total METs per week times the duration of exercise
         Ex_rec = as.factor(ifelse(MET_min >= 500, "Sufficient", "Insufficient")),
            # Meeting activity levels (i.e., sufficient vs insufficient)
         Ex_3cat = as.factor(ifelse(MET_min < 290, 1,
                              ifelse(MET_min < 500 & MET_min >= 290, 2,3))),
         Ex_4cats = as.factor(ifelse(MET_min < 290, "Sed",
                              ifelse(MET_min < 500 & MET_min >= 290, "Mod",
                              ifelse(MET_min < 1000 & MET_min >= 500, "Active", 
                              ifelse(MET_min < 2000 & MET_min >= 1000, "Super", NA))))),
         Ex_3catW = as.factor(ifelse(MET_min_W < 290, 1,
                              ifelse(MET_min_W < 500 & MET_min_W >= 290, 2,3))),
         Ex_4catsW = as.factor(ifelse(MET_min_W < 290, "Sed",
                              ifelse(MET_min_W < 500 & MET_min_W >= 290, "Mod",
                              ifelse(MET_min_W < 1000 & MET_min_W >= 500, "Active", 
                              ifelse(MET_min_W < 2500 & MET_min_W >= 1000, "Super", NA))))),
# 3 godin (HCS) categories converted to MET_min 
    # Other Variables 
         HCS_win = (God_mod*5) + (God_stren*9),
         HCS3cat = as.factor(ifelse(HCS_win < 14, "Insufficient",
                              ifelse(HCS_win < 24 & HCS_win >= 290, "Moderate", "Active"))),
         Yr5_Military = as.factor(ifelse(Years_in_Military >= 5, "5+", "<5")),
         Active_PA = as.factor(ifelse(Ex_3cat == 3,1,0)),
         Moderate_PA = as.factor(ifelse(Ex_3cat == 2,1,0)),
         Insuf_PA = as.factor(ifelse(Ex_3cat == 2,1,0)),
         Total_HC = Any_Disability + Arthritis + Cancer + Chron_pain + Liv_dis +
                    Diabetes + Hrt_dis + Hrt_atk + High_chol + High_bld_press +
                    Kid_dis + Migrane + MS + Osteoporosis + Rhum_arth + Stroke +
                    LT_MDD + LT_PTSD + LT_AUD + LT_DUD + LT_NicotineDep,
         Total_PHC = Any_Disability + Arthritis + Cancer + Chron_pain + Liv_dis +
                    Diabetes + Hrt_dis + Hrt_atk + High_chol + High_bld_press +
                    Kid_dis + Migrane + MS + Osteoporosis + Rhum_arth + Stroke,
        Total_MHC = LT_MDD + LT_PTSD + LT_AUD + LT_DUD + LT_NicotineDep,
        No_Condition = ifelse(Any_MHC == 1 | Any_PHC ==1, 0,1)
    ) %>%
mutate(thesis_NHRVS,
      #Physical health variables
           Any_Disability = as.factor(Any_Disability),
           Arthritis = as.factor(Arthritis),
           Athsma = as.factor(Athsma),
           Cancer = as.factor(Cancer),
           Chron_pain = as.factor(Chron_pain),
           Liv_dis = as.factor(Liv_dis),
           Diabetes = as.factor(Diabetes),
           Hrt_dis = as.factor(Hrt_dis),
           Hrt_atk = as.factor(Hrt_atk),
           High_chol = as.factor(High_chol),
           High_bld_press = as.factor(High_bld_press),
           Kid_dis = as.factor(Kid_dis),
           Migrane = as.factor(Migrane),
           MS = as.factor(MS),
           Osteoporosis = as.factor(Osteoporosis),
           Rhum_arth = as.factor(Rhum_arth),
           Stroke = as.factor(Stroke),
           Ex_3cat = as.factor(Ex_3cat),  
           Male_Gender = as.factor(Male_Gender), 
           Married_Partnered = as.factor(Married_Partnered),
           White_Race = as.factor(White_Race),
           College = as.factor(College),
           Income_60k_plus = as.factor(Income_60k_plus),
           YN_work = as.factor(YN_work),
           Combat_Veteran = as.factor(Combat_Veteran),
           Any_MHC = as.factor(Any_MHC),
           Any_PHC = as.factor(Any_PHC),
           god2cat = as.factor(god2cat),
      #Mental health variables
          LT_Suicide_4cat = as.factor(LT_Suicide_4cat),
          LT_MDD = as.factor(LT_MDD),
          LT_PTSD = as.factor(LT_PTSD),
          LT_AUD = as.factor(LT_AUD),
          LT_DUD = as.factor(LT_DUD),
          LT_NicotineDep = as.factor(LT_NicotineDep)
    )
thesis_NHRVS <- mutate(thesis_NHRVS, 
        Ex_3cat = recode(Ex_3cat,
                         "1" = "Insufficient",
                         "2" = "Moderate",
                         "3" = "Active"),
        Married_Partnered = recode(Married_Partnered,
                         "0" = "Married_Partnered",
                         "1" = "Single"),
        Male_Gender = as.factor(Male_Gender),
        Male_Gender = recode(Male_Gender,
                         "0" = "Female",
                         "1" = "Male"),
        White_Race = recode(White_Race,
                         "0" = "Not_White",
                         "1" = "White"),
        College = recode(College,
                         "0" = "No_Colege",
                         "1" = "Some_Colege"),
        Income_60k_plus = recode(Income_60k_plus,
                         "0" = "Under_60k",
                         "1" = "OVer_60k"),
        YN_work = recode(YN_work,
                         "1" = "No_Work",
                         "2" = "Working"),
        Combat_Veteran = as.factor(Combat_Veteran),
        Combat_Veteran = recode(Combat_Veteran,
                         "0" = "No_Combat",
                         "1" = "Combat"),
        Any_MHC = recode(Any_MHC,
                         "0" = "No_con",
                         "1" = "MHC"),
        Any_PHC = recode(Any_PHC,
                         "0" = "No_con",
                         "1" = "PHC"),
        LT_Suicide_4cat = as.factor(LT_Suicide_4cat),
        LT_Suicidal = recode(LT_Suicide_4cat,
                         "0" = "0",
                         "1" = "0",
                         "2" = "1",
                         "3" = "1"
                             ))

#Filter out NA values
thesis_NHRVS <- thesis_NHRVS %>%
  filter(!is.na(Ex_rec)) %>%
  filter(!is.na(Ex_3cat)) %>%
  filter(!is.na(MCS)) %>%
  filter(!is.na(PCS)) %>%
  filter(!is.na(BMI)) %>%
  filter(!is.na(Any_Disability)) %>%
  filter(!is.na(Arthritis)) %>%
  filter(!is.na(Cancer)) %>%
  filter(!is.na(Chron_pain)) %>%
  filter(!is.na(Liv_dis)) %>%
  filter(!is.na(Diabetes)) %>%
  filter(!is.na(Hrt_dis)) %>%
  filter(!is.na(Hrt_atk)) %>%
  filter(!is.na(High_chol)) %>%
  filter(!is.na(High_bld_press)) %>%
  filter(!is.na(Kid_dis)) %>%
  filter(!is.na(Migrane)) %>%
  filter(!is.na(MS)) %>%
  filter(!is.na(Osteoporosis)) %>%
  filter(!is.na(Rhum_arth)) %>%
  filter(!is.na(Stroke)) %>%
  filter(!is.na(LT_MDD)) %>%
  filter(!is.na(LT_PTSD)) %>%
  filter(!is.na(LT_AUD)) %>%
  filter(!is.na(LT_DUD)) %>%
  filter(!is.na(LT_NicotineDep)) %>%
  filter(!is.na(LT_Suicidal))
#$View(thesis_NHRVS)
thesis_NHRVS
library(MASS)
library(nnet)
```

### Create Tables for Multinomial Logistic Regression Output

The code below manually creates a table for the 3 blocks of the multinomial logistic regression. 
```{r,message=FALSE}
#1. Import tables
  r2_change <- read_csv("~/Desktop/Coding/data/R2change.csv")
  cov.SF8_OR_tab <- read.csv("~/Desktop/Coding/data/SF8.cov_OR_tab.csv")
  Ins_Mod <- read_csv("~/Desktop/Coding/data/Ins_Mod.csv")
  Ins_Act <- read_csv("~/Desktop/Coding/data/Ins_Act.csv")
  Act_Mod <- read_csv( "~/Desktop/Coding/data/Act_Mod.csv")
```


```{r}
#2. Create dataframes to be merged.
    OR_Table = data.frame(
      Ins_Act$variable, Ins_Act$ci, Ins_Mod$ci, Act_Mod$ci,Act_Mod$r2_change
      )
    colnames(OR_Table) <- c("Variable","IvA_ODDS",
                          "IvM_ODDS", "AvM_ODDS",
                          "R2_Change")
    
#3. Create a block 3 row
  Block_3 = cbind(
    Variable = "Block 3: Health Conditions R^2 range = 0.032 - 0.052",
    IvA_ODDS = NA,
    IvM_ODDS = NA,
    AvM_ODDS = NA,
    R2_Change = NA
  )

#4. pull out values from covariates table
  Cov_table = data.frame(
    cov.SF8_OR_tab$variable,
    cov.SF8_OR_tab$IvA_ODDS, 
    cov.SF8_OR_tab$IvM_ODDS,
    cov.SF8_OR_tab$AvM_ODDS
  )
  Cov_table$R2_Change = NA
  colnames(Cov_table) <- c("Variable","IvA_ODDS",
                          "IvM_ODDS", "AvM_ODDS",
                          "R2_Change")

#5. Merge all the data frames
  OR_Table <- rbind(Cov_table,Block_3,OR_Table)

#6. update R2 change df and add it to OR tab
  r2_change = rbind(r2_change[1:6,],NA,r2_change[7:33,])
  OR_Table <- cbind(OR_Table[,1:4],r2_change)
#6. Rename columns for table 
  colnames(OR_Table) <- c("Variable","Insufficient vs Sufficient ORs",
                          "Insufficient vs Moderate ORs", "Active vs Moderate ORs", "R^2 Change")
  
  
#7. View Table
    knitr::kable(OR_Table) %>%
          kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

#8 Export Table
    write_csv(OR_Table,"~/Desktop/Coding/data/Thesis_OR_Table.csv")
```
